name: SeattlePotGuy
favicon: null
layout_spectrum: 0.25656
typography_spectrum: 0.5478480902966112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce0e3'
    - '#251f27'
    - '#7cb4c1'
    - '#5f819f'
    - '#404c6a'
  brandStrength: 0.6875
  lightness: 0.5523791378363967
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
