name: SeattlePotGuy
favicon: null
layout_spectrum: 0.25656
typography_spectrum: 0.5478480902966112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8713218010962009
  lightness: 0.5523791378363967
  saturation: 0.6664092559367418
  rhythmicContrast: 0.2281279049348086
purpose: []
